### ISSUE TITLE
nicht möglich zu float zu convertieren

### ISSUE THREAD

**Issue by nimarb** [likyng/pyha#1]
bekommst du bei [hier](https://github.com/likyng/pyha/blob/rob-ha4/timezone.py#L71) kein fehler bei den Zeilen in timezone.csv deren Zone UTC ist, weil dort regio[2] = "" ist?

**Comment by ro-bb** [comment]
das kann nicht passieren, weil [die if abfrage](https://github.com/likyng/pyha/blob/rob-ha4/timezone.py#L68) davor das rausfilter:

```
    elif region[2] == "":
        continue
```

**Comment by nimarb** [comment]
stimmt!
